baseURL: https://www.fragmentis-vitae.org/ # if your site is in 'https', then make sure your base url isn't written using 'http' otherwise your sitemap would contain http (as opposeed to https) URLs. This would affect Google indexing of your URLs.
title: "Fragments #KH50"
paginate: 5
theme: charlolamode

menu:
  main:
    - name: Le projet
      url: /presentation/
      weight: 10
    - name: "Crowdfunding"
      url: /crowdfunding/
      weight: 15
    - name: "Mémorial #KH50"
      url: /monument/
      weight: 20
    - name: Témoignez
      url: /temoignages/
      weight: 30
    - name: Porteurs du projet
      url: /porteurs-projet/
      weight: 40
    - name: Soutiens
      url: /soutiens/
      weight: 50
    - name: "Shop"
      url: /shop/
      weight: 60
    - name: Actus
      url: /events-actus/
      weight: 70
    - name: Presse
      url: /espace-presse/
      weight: 80
    - name: Contact
      url: /contact/
      weight: 90

# - name: Contact
#   url: /contact/
#   weight: 30
# - name: Articles
#   url: /articles/
#   weight: 20
# - name: Projects
#   url: /projects/
#   weight: 15

# - name: Categories
#   url: /categories/
#   weight: 10
# - name: new Tab
#   url: /newtab/
#   weight: defines order of tabs

params:
  author: loiklak
  description:
    "Le projet FRAGMENTS #KH50 a été initié par des descendants de familles ayant fui le Cambodge pour se réfugier en France afin de mener un travail de mémoire.  Du fait de l’exil et de la guerre, chacun ne possède que quelques fragments de l’histoire de sa famille.

    Porté par l’association Loi 1901, FRAGMENTIS VITAE ASIA, reconnue d’intérêt général, le projet a pour objectif  rassembler ces fragments d’histoires personnelles pour reconstituer la mémoire collective"

  defaultTheme: auto
  # disableThemeToggle: true
  displayFullLangName: true
  ShowCodeCopyButtons: true
  logoUrl: "/images/fragment-rond.svg"

  profileMode:
    # Disable to populate home page with 'mainSections' content
    enabled: true
    
    title: "Fragments #KH50"
    description:
      "Le projet FRAGMENTS #KH50 a été initié par des descendants de familles ayant fui le Cambodge pour se réfugier en France afin de mener un travail de mémoire.  Du fait de l’exil et de la guerre, chacun ne possède que quelques fragments de l’histoire de sa famille.\n

      Porté par l’association Loi 1901, FRAGMENTIS VITAE ASIA, reconnue d’intérêt général, le projet a pour objectif  rassembler ces fragments d’histoires personnelles pour reconstituer la mémoire collective
      "
    imageUrl: "/images/fragment-rond.svg"
    imageTitle: logo fragments
    imageWidth: 300
    imageHeight: 300
    buttons:
      - name: Adhérer à l'association 🤝
        url: https://www.helloasso.com/associations/fragmentis-vitae-asia-bussy-saint-georges/adhesions/adhesion-2026
      - name: Faire un don ❤️
        url: https://www.helloasso.com/associations/fragmentis-vitae-asia-bussy-saint-georges/formulaires/1
      - name: Témoigner 🗣️
        url: /temoignages/

  socialIcons:
    - name: linkedin
      url: "https://www.linkedin.com/showcase/fragments-kh50/"
    - name: twitter
      url: "https://twitter.com/FragmentisVitae"
    - name: facebook
      url: "https://www.facebook.com/Fragments.kh50"
    - name: instagram
      url: "https://www.instagram.com/fragments_kh50/"

  # change favicon in images folder (icon for web tab)
  assets:
    favicon: "/images/favicon.ico"
    favicon16x16: "/images/favicon-16x16.png"
    favicon32x32: "/images/favicon-32x32.png"
    apple_touch_icon: "/images/apple-touch-icon.png"
    safari_pinned_tab: "/images/apple-touch-icon.png"

copyright: © 2023 FragmentisVitaeAsia

enableInlineShortcodes: true
enableRobotsTXT: true
enableEmoji: true
pygmentsUseClasses: true

minify:
  disableXML: true

markup:
  goldmark:
    renderer:
      unsafe: true

buildFuture: true
